country: taiwan
owner: frank

# 數組用法
likes:
  - game
  - movie
likes2: [music, sleep]


server:
  port: 8080
#  servlet:#    context-path: frank

logging:  level:
    root: error
    
spring:  datasource:     driver-class-name: com.mysql.cj.jdbc.Driver 
     url: jdbc:mysql://localhost:3306/springbootreview?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
     username: root
     password: mm12583
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    